-- MySQL Script generated by MySQL Workbench
-- 03/07/16 12:59:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema evidence_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema evidence_db
-- -----------------------------------------------------
Drop schema  if exists evidence_db;
CREATE SCHEMA IF NOT EXISTS `evidence_db` DEFAULT CHARACTER SET utf8 ;
USE `evidence_db` ;

-- -----------------------------------------------------
-- Table `evidence_db`.`office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evidence_db`.`office` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `evidence_db`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evidence_db`.`project` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  `description` TEXT NULL DEFAULT NULL COMMENT '',
  `project_start` DATE NULL DEFAULT NULL COMMENT '',
  `project_end` DATE NULL DEFAULT NULL COMMENT '',
  `successful` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `evidence_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evidence_db`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `status` INT(11) NOT NULL COMMENT '',
  `name` VARCHAR(25) NOT NULL COMMENT '',
  `surname` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `contract_type` VARCHAR(20) NOT NULL COMMENT '',
  `contract_start` DATE NULL DEFAULT NULL COMMENT '',
  `contract_end` DATE NULL DEFAULT NULL COMMENT '',
  `id_project` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `evidence_db`.`work_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evidence_db`.`work_time` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_user` BIGINT NULL COMMENT '',
  `id_project` BIGINT NULL COMMENT '',
  `id_office` BIGINT NULL COMMENT '',
  `start_time` TIME NULL COMMENT '',
  `end_time` TIME NULL COMMENT '',
  `sum_time` TIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `id_user_key_idx` (`id_user` ASC)  COMMENT '',
  INDEX `id_office_key_idx` (`id_office` ASC)  COMMENT '',
  INDEX `id_project_key_idx` (`id_project` ASC)  COMMENT '',
  CONSTRAINT `id_office_key`
    FOREIGN KEY (`id_office`)
    REFERENCES `evidence_db`.`office` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_user_key`
    FOREIGN KEY (`id_user`)
    REFERENCES `evidence_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_project_key`
    FOREIGN KEY (`id_project`)
    REFERENCES `evidence_db`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
